import FloatingSearchbar from "@/components/FloatingSearchbar"
import Header from "@/components/Header"
import Loader from "@/components/Loader"
import LoginDialog from "@/components/LoginDialog"
import Sidebar from "@/components/Sidebar"
import Script from "next/script"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <title>Gabutlab</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="/css/style.css"/>
      </head>

      <body id="body">
        <FloatingSearchbar/>

        <Loader/>

        <Header/>

        <button id="scrollToTopBtn" title="Scroll to top">▲</button>

        <main>
          <Sidebar/>

          {children}
        </main>

        <footer>
          <div>
            <span>2024 | Gabutlab</span>
          </div>
        </footer>

        <Script src="/js/articles.js"/>
        <Script src="/js/main.js"/>
      </body>
    </html>
  )
}
